name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check rustfmt and common mistakes
      run: |
        cargo fmt -- --check
        cargo clippy --all-targets -- --deny warnings
    - name: Set up python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch
    - name: Run tests
      run: cargo test
