name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{matrix.rust}}
        components: rustfmt, clippy
    - run: cargo fmt -- --check
    - run: cargo clippy --all-targets -- --deny warnings
    - run: cargo test
